### ISSUE TITLE
New targets: AVM FritzBox! 7312 7412 et al.

### ISSUE THREAD

**Issue by misanthropos** [Moorviper/meshviewer_hwpics#13]
This is less of an issue and more a way to contact you to ask to provide those images, or give maybe some hints how to produce them myself.
Background ist ffm.freifunk.net, which recently provided firmwares for a couple of AVM machines.

**Comment by Moorviper** [comment]
yeah i can draw them tomorrow actually i have some time :D

**Comment by misanthropos** [comment]
I have created an image - could you add it to the repository?

[avm-fritz-box-7312.svg](https://drive.google.com/open?id=1qQuoalPIHboNzSZ6iKmoMOv6PdLEllwY)

**Comment by misanthropos** [comment]
Nevermind... I created a repository.
https://github.com/misanthropos/router-pictures
